/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f407_gpio.h"
#include "stm32f407_sysconf.h"
#include "stm32f407_rcc.h"
#include "arm4.h"

int main()
{
	//SCB->CPACR |= ((3UL << 10*2)|(3UL << 11*2));
	uint8_t val ;
	RCC_CLKInitTypeDef div;
	RCC_HSIConfig(RCC_HSI_ON);
	div.AHBdiv = AHB_SYSCLK_DIV2 ;
	div.APB1div = APB1_SYSCLK_DIV8 ;
	div.APB2div = APB2_SYSCLK_DIV16 ;

	RCC_SetPrescaler(div);
	//RCC_DeInitPrescaler();




	RCC_SetSystemClockSwitch(HSI_OSC_SYSTEM_CLK);
	val = RCC_GetOscillatorSoucre();
	RCC_GetSYSCLK() ;
	RCC_GetHCLK(div) ;
	RCC_GetPLCLK1(div);
	RCC_GetPLCLK2(div);


}

